services:
  - type: web
    name: wordpress-tool
    env: docker
    plan: free
    envVars:
      - key: WORDPRESS_DB_HOST
        value: "tu-host-de-aiven:puerto"
      - key: WORDPRESS_DB_USER
        value: "tu-usuario"
      - key: WORDPRESS_DB_NAME
        value: "tu-nombre-de-base-de-datos"
