services:
  - type: web
    name: wordpress-tool
    env: docker
    plan: free
    envVars:
      - key: WORDPRESS_DB_HOST
        value: "javer-grupojaver-ae8e.d.aivencloud.com:22293"
      - key: WORDPRESS_DB_USER
        value: "avnadmin"
      - key: WORDPRESS_DB_NAME
        value: "defaultdb"
